services:
  atheon-in-action:
    build:
      context: .
      target: runtime
    ports:
      - 8698:7860
    networks:
      - atheon-in-action-net
      - atheon-gateway-net
    volumes:
      - ./app:/app
    environment:
      ATHEON_API_KEY: "${ATHEON_API_KEY}"
      GROQ_API_KEY: "${GROQ_API_KEY}"
      MONGO_URI: "${MONGO_URI}"
      OPENBLAS_NUM_THREADS: "${OPENBLAS_NUM_THREADS:-4}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://atheon-in-action/health"]
      interval: 60s
      timeout: 5s
      retries: 3

networks:
  atheon-in-action-net:
    name: atheon-in-action-network
  atheon-gateway-net:
    name: atheon-gateway-network
    external: true
